name: Test Custom Container

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: scripts/install_dependencies.sh

      - name: Build and test
        run: |
          ci/run_test.sh
