name: Using custom container image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/ronekko/ubuntu22.04-cpp:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test
        run: |
          ci/run_test.sh
