name: Using custom container image

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/ronekko/ubuntu22.04-cpp:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "5GB"
          append-timestamp: false
          key: ${{ github.workflow }}-${{ github.ref_name }}
          restore-keys: |
            ${{ github.workflow }}-${{ github.ref_name }}
            ${{ github.workflow }}-main
            ${{ github.workflow }}-

      - name: Build and test
        run: |
          ci/run_test.sh

      - name: Cache ccache directory (direct actions/cache test)
        uses: actions/cache@v4
        with:
          path: /__w/workflow_using_custom_container_image/workflow_using_custom_container_image/.ccache # 完全パス指定
          key: ccache-direct-test-${{ github.workflow }}-${{ github.ref_name }}
          restore-keys: |
            ccache-direct-test-${{ github.workflow }}-main
            ccache-direct-test-${{ github.workflow }}-
