name: Using custom container image

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/ronekko/ubuntu22.04-cpp:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "5GB"
          key: ${{ github.workflow }}-${{ github.ref_name }}
          restore-keys: |
            ${{ github.workflow }}-${{ github.ref_name }}
            ${{ github.workflow }}-main
            ${{ github.workflow }}-

      - name: Build and test
        run: |
          ci/run_test.sh
