name: Using default containerimage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: scripts/install_dependencies.sh

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "5GB"
          append-timestamp: false
          key: ${{ github.workflow }}-${{ github.ref_name }}
          restore-keys: |
            ${{ github.workflow }}-${{ github.ref_name }}
            ${{ github.workflow }}-main
            ${{ github.workflow }}-

      - name: Build and test
        run: |
          ci/run_test.sh
